development:
  adapter: postgresql
  encoding: unicode
  database: lunchzilla_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: lunchzilla_test
  pool: 5
  username: postgres
  password: postgres